version: '3'

services:
  crm_app:
    build: .
    restart: always
    container_name: 'CrmWizzard'
    command: /bin/bash -c "poetry run python manage.py collectstatic --noinput && poetry run python manage.py migrate && poetry run uvicorn app.asgi:application --host 0.0.0.0 --port 8001 --workers 4"
    volumes:
      - .:/crm
      - static:/crm/static
      - media:/crm/media
    ports:
      - 8001:8001
    network_mode: host

  nginx_app:
    image: nginx:latest
    ports:
      - "85:81"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf.template
      - static:/crm/static
      - media:/crm/media
    depends_on:
      - crm_app
    network_mode: host


volumes:
  static:
  media:

