# Generated by Django 5.0.6 on 2024-06-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='price_by_order',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Цена при покупке'),
        ),
    ]
